# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://playforward-ee8c.onrender.com/")
    self.driver.set_window_size(948, 1036)
    self.driver.find_element(By.LINK_TEXT, "Potraži igračku").click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".rounded-lg:nth-child(1)"))).click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "← Nazad na igračke"))).click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".rounded:nth-child(2)"))).click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(2)")
    dropdown.find_element(By.XPATH, "//option[. = 'Sportska oprema']").click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "option:nth-child(4)"))).click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".object-cover").click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "← Nazad na igračke"))).click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".rounded:nth-child(3)"))).click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".rounded:nth-child(3)")
    dropdown.find_element(By.XPATH, "//option[. = 'Sortiraj: Najnovije prvo']").click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".border:nth-child(3) > option:nth-child(2)"))).click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(3) > option:nth-child(2)").click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".rounded:nth-child(2)"))).click()
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-lg:nth-child(2)").click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "← Nazad na igračke"))).click()
    WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".md\\3Aw-1\\/3"))).click()
    self.driver.find_element(By.CSS_SELECTOR, ".md\\3Aw-1\\/3").click()
    search_box = WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".md\\3Aw-1\\/3")))
    search_box.clear()
    search_box.send_keys("lo")
    self.driver.execute_script("""arguments[0].dispatchEvent(new Event('input', { bubbles: true }));""", search_box)
    self.driver.find_element(By.CSS_SELECTOR, ".object-cover").click()
  
