spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/playforward
    username: postgres
    password: <tvoja_lozinka_za_pgAdmin>
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
