server.port=${PORT:8080}
server.sevlet.context-path=/api

spring.datasource.password=${DB_PASS:OFgDdZhAZumrNTdvbDnHoXd21g8XNyQ4}
spring.datasource.username=${DB_USERNAME:playforward_db_user}
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d469v1emcj7s73be68qg-a:5432/playforward_db?sslmode=require}
spring.datasource.driverClassName=${DB_DRIVER:org.postgresql.Driver}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
app.frontend.url=https://playforward.onrender.com
