server.port=${PORT:8080}
server.sevlet.context-path=/api

spring.datasource.password=${DB_PASS:VDMLFjk35Bk0XcgDb9UVljoKFSP4q4JI}
spring.datasource.username=${DB_USERNAME:playforward_db_user}
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d5egs4dactks73c7lplg-a:5432/playforward_db_v9gq?sslmode=require}
spring.datasource.driverClassName=${DB_DRIVER:org.postgresql.Driver}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


app.frontend.url=https://playforward.onrender.com

# JWT Configuration for production
app.jwt.secret=${JWT_SECRET:PlayForward2025ProductionJWTSecretKeyMustBeSecureMinimum256BitsLongForSecurity}
app.jwt.expiration-ms=86400000
